"""
Exporter service — renders a FinalDecision as Markdown or PDF.
"""

from __future__ import annotations

import logging
from datetime import datetime

from app.schemas.final_decision import FinalDecision

logger = logging.getLogger("agentboard.exporter")


def render_markdown(decision: FinalDecision) -> str:
    """Render a FinalDecision as a Markdown document."""
    lines: list[str] = []
    ts = decision.created_at.strftime("%Y-%m-%d %H:%M UTC") \
        if decision.created_at else "Unknown"

    lines.append(f"# AgentBoard Decision Report")
    lines.append(f"")
    lines.append(f"**Thread ID:** `{decision.thread_id}`  ")
    lines.append(f"**Date:** {ts}  ")
    lines.append(f"**Rounds:** {decision.total_rounds}  ")
    lines.append(f"**Termination:** {decision.termination_reason.replace('_', ' ').title()}")
    if decision.query:
        lines.append(f"\n## Query\n\n{decision.query}")

    lines.append(f"\n## Decision\n\n{decision.decision}")
    lines.append(f"\n## Rationale\n\n{decision.rationale_summary}")

    lines.append(f"\n## Scores\n")
    lines.append(f"| Metric | Score |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Confidence | {decision.confidence_score:.0%} |")
    lines.append(f"| Agreement | {decision.agreement_score:.0%} |")

    if decision.risk_flags:
        lines.append(f"\n## Risk Flags\n")
        for flag in decision.risk_flags:
            lines.append(f"- {flag}")

    if decision.alternatives:
        lines.append(f"\n## Alternatives Considered\n")
        for i, alt in enumerate(decision.alternatives, 1):
            lines.append(f"{i}. {alt}")

    if decision.key_disagreements:
        lines.append(f"\n## Key Disagreements\n")
        for d in decision.key_disagreements:
            lines.append(f"- {d}")

    if decision.minority_report:
        lines.append(f"\n## Minority Report\n")
        for entry in decision.minority_report:
            lines.append(f"### {entry.agent_name} ({entry.confidence_score:.0%} confidence)\n")
            lines.append(f"**Position:** {entry.final_position}\n")
            lines.append(f"**Dissent:** {entry.dissent_reason}\n")

    if decision.agent_contribution_scores:
        lines.append(f"\n## Agent Contribution Scores\n")
        lines.append(f"| Agent | Score |")
        lines.append(f"|-------|-------|")
        for agent, score in sorted(
            decision.agent_contribution_scores.items(), key=lambda x: x[1], reverse=True
        ):
            lines.append(f"| {agent} | {score:.0%} |")

    if decision.dissenting_opinions:
        lines.append(f"\n## Dissenting Opinions\n")
        for op in decision.dissenting_opinions:
            lines.append(f"- {op}")

    if decision.debate_trace:
        lines.append(f"\n## Debate Trace Summary\n")
        lines.append(f"| Round | Agents | Critiques |")
        lines.append(f"|-------|--------|-----------|")
        for round_data in decision.debate_trace:
            agents_list = ", ".join(o.agent_name for o in round_data.agent_outputs)
            lines.append(
                f"| {round_data.round_number} | {agents_list or '-'} | {len(round_data.critiques)} |"
            )

    lines.append(f"\n---\n*Generated by AgentBoard*")
    return "\n".join(lines)


def render_html(decision: FinalDecision) -> str:
    """Render a FinalDecision as an HTML document suitable for PDF conversion."""
    import html as html_lib

    def esc(s: str) -> str:
        return html_lib.escape(s or "")

    ts = decision.created_at.strftime("%Y-%m-%d %H:%M UTC") \
        if decision.created_at else "Unknown"

    body_parts: list[str] = []

    body_parts.append(f"<h1>AgentBoard Decision Report</h1>")
    body_parts.append(
        f"<p><strong>Thread:</strong> <code>{esc(decision.thread_id)}</code> &nbsp; "
        f"<strong>Date:</strong> {esc(ts)} &nbsp; "
        f"<strong>Rounds:</strong> {decision.total_rounds}</p>"
    )
    if decision.query:
        body_parts.append(f"<h2>Query</h2><p>{esc(decision.query)}</p>")
    body_parts.append(f"<h2>Decision</h2><p class='decision'>{esc(decision.decision)}</p>")
    body_parts.append(f"<h2>Rationale</h2><p>{esc(decision.rationale_summary)}</p>")

    body_parts.append(
        f"<h2>Scores</h2>"
        f"<table><tr><th>Confidence</th><th>Agreement</th></tr>"
        f"<tr><td>{decision.confidence_score:.0%}</td><td>{decision.agreement_score:.0%}</td></tr></table>"
    )

    if decision.risk_flags:
        items = "".join(f"<li>{esc(f)}</li>" for f in decision.risk_flags)
        body_parts.append(f"<h2>Risk Flags</h2><ul>{items}</ul>")

    if decision.alternatives:
        items = "".join(f"<li>{esc(a)}</li>" for a in decision.alternatives)
        body_parts.append(f"<h2>Alternatives Considered</h2><ol>{items}</ol>")

    if decision.key_disagreements:
        items = "".join(f"<li>{esc(d)}</li>" for d in decision.key_disagreements)
        body_parts.append(f"<h2>Key Disagreements</h2><ul>{items}</ul>")

    if decision.minority_report:
        parts = []
        for entry in decision.minority_report:
            parts.append(
                f"<div class='minority'>"
                f"<strong>{esc(entry.agent_name)}</strong> ({entry.confidence_score:.0%} confidence)<br>"
                f"<em>Position:</em> {esc(entry.final_position)}<br>"
                f"<em>Dissent:</em> {esc(entry.dissent_reason)}"
                f"</div>"
            )
        body_parts.append(f"<h2>Minority Report</h2>{''.join(parts)}")

    if decision.agent_contribution_scores:
        rows = "".join(
            f"<tr><td>{esc(a)}</td><td>{s:.0%}</td></tr>"
            for a, s in sorted(decision.agent_contribution_scores.items(), key=lambda x: x[1], reverse=True)
        )
        body_parts.append(
            f"<h2>Agent Contributions</h2>"
            f"<table><tr><th>Agent</th><th>Score</th></tr>{rows}</table>"
        )

    if decision.dissenting_opinions:
        items = "".join(f"<li>{esc(op)}</li>" for op in decision.dissenting_opinions)
        body_parts.append(f"<h2>Dissenting Opinions</h2><ul>{items}</ul>")

    body = "\n".join(body_parts)

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>AgentBoard Decision — {esc(decision.thread_id)}</title>
  <style>
    body {{ font-family: Georgia, serif; max-width: 800px; margin: 40px auto; color: #1a1a1a; line-height: 1.6; }}
    h1 {{ font-size: 1.8em; border-bottom: 2px solid #333; padding-bottom: .4em; }}
    h2 {{ font-size: 1.2em; color: #333; margin-top: 1.5em; border-bottom: 1px solid #ccc; }}
    .decision {{ font-size: 1.1em; font-weight: bold; padding: 12px; background: #f7f7ff; border-left: 4px solid #4444ff; }}
    table {{ border-collapse: collapse; width: 100%; margin: .5em 0; }}
    th, td {{ border: 1px solid #ccc; padding: 6px 12px; text-align: left; }}
    th {{ background: #f0f0f0; }}
    .minority {{ margin: 8px 0; padding: 10px; background: #fffbe6; border-left: 4px solid #f0a500; }}
    code {{ background: #f0f0f0; padding: 2px 4px; border-radius: 3px; font-size: .9em; }}
    footer {{ margin-top: 3em; color: #999; font-size: .8em; text-align: center; }}
  </style>
</head>
<body>
{body}
<footer>Generated by AgentBoard</footer>
</body>
</html>"""


def render_pdf(decision: FinalDecision) -> bytes:
    """Convert the HTML export to a PDF using WeasyPrint."""
    try:
        from weasyprint import HTML  # type: ignore[import-untyped]
    except ImportError as exc:
        raise RuntimeError("WeasyPrint is not installed. Run: pip install weasyprint") from exc

    html_content = render_html(decision)
    return HTML(string=html_content).write_pdf()
